pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'node:6-alpine' 
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'npm install'
                echo 'finished build'
            }
        }
        stage('Tests') {
            agent {
                docker {
                    image 'node:10-alpine'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'npm test -- -u'
                echo 'Finished backend Tests'
            }
        }
        stage('Code Coverage') {
            agent {
                docker {
                    image 'node:10-alpine'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh  'npm test -- --coverage --watchall=false'               
                echo 'Finished Code Coverage'
            }
        }
        
        stage('Static Analysis') {
            agent {
                docker {
                    image 'node:10-alpine'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'npm test -- --reporters="default" --watchAll'
                sh 'f'
                sh 'q'
                echo 'Finished Static Analysis'
            }
        }
        
        
    }
}